# SQL-Based Hotel Booking Data Analysis

This project performs SQL-based data analysis on a hotel booking dataset using Python, Pandas, and SQLite in Google Colab.

# Import Libraries

In [ ]:
import pandas as pd
import sqlite3

# Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Load Dataset

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Data Set/Project Dataset 3.xlsx')

# View Dataset

In [ ]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

# Missing Values Check

In [ ]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

# Handle Missing Values

In [ ]:
df['CouponCode'] = df['CouponCode'].fillna('Not use the Coupon')

# Recheck Missing Values

In [ ]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

# Check the Duplicate

In [ ]:
df.duplicated().sum()

np.int64(0)

The dataset contained missing values only in the CouponCode column. Since not all customers use coupon codes during purchases, the missing values were replaced with 'Not use the Coupon'. Duplicate records were also checked, and no duplicate rows were found in the dataset.

# Save Cleaned Dataset

In [ ]:
df.to_excel('/content/drive/MyDrive/Data Set/Project_3_Cleaned_Ecommerce_Dataset.xlsx', index=False)

# Create SQL Connection

In [ ]:
conn = sqlite3.connect(':memory:')

# Convert DataFrame to SQL Table

In [ ]:
df.to_sql('ecommerce_data', conn, index=False, if_exists='replace')

1200

The cleaned dataset was converted into an SQL table using SQLite to perform SQL-based data analysis queries.

# View Dataset Using SELECT

In [ ]:
query = """
SELECT *
FROM ecommerce_data
LIMIT 6
"""

pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23 00:00:00,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72

# WHERE Clause Analysis

In [ ]:
query = """
SELECT *
FROM ecommerce_data
WHERE OrderStatus = 'Delivered'
"""

pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200015,2023-07-17 00:00:00,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,Not use the Coupon,Google,473.96
2,ORD200021,2024-11-17 00:00:00,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,Not use the Coupon,Google,1371.80
3,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
4,ORD200025,2024-07-24 00:00:00,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,ORD201166,2023-07-31 00:00:00,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
227,ORD201168,2023-04-08 00:00:00,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
228,ORD201171,2023-08-28 00:00:00,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
229,ORD201187,2024-03-13 00:00:00,C26340,Desk,2,184.60,562 Main St,Gift Card,Delivered,TRK59962703,7,WINTER15,Email,369.20
230,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

# ORDER BY Analysis

In [ ]:
query = """
SELECT Product, TotalPrice
FROM ecommerce_data
ORDER BY TotalPrice DESC
LIMIT 10
"""

pd.read_sql(query, conn)

   Product  TotalPrice
0   Tablet     3456.40
1  Monitor     3390.95
2   Laptop     3390.80
3    Chair     3384.90
4   Tablet     3370.20
5  Printer     3353.75
6   Laptop     3352.40
7  Printer     3334.00
8    Phone     3322.55
9   Laptop     3313.90

# GROUP BY Analysis

In [ ]:
query = """
SELECT Product, COUNT(*) AS TotalOrders
FROM ecommerce_data
GROUP BY Product
"""

pd.read_sql(query, conn)

   Product  TotalOrders
0    Chair          178
1     Desk          170
2   Laptop          173
3  Monitor          163
4    Phone          156
5  Printer          181
6   Tablet          179

# COUNT Aggregation

In [ ]:
query = """
SELECT PaymentMethod, COUNT(*) AS TotalPayments
FROM ecommerce_data
GROUP BY PaymentMethod
"""

pd.read_sql(query, conn)

  PaymentMethod  TotalPayments
0          Cash            246
1   Credit Card            234
2    Debit Card            232
3     Gift Card            230
4        Online            258

# SUM Aggregation

In [ ]:
query = """
SELECT Product, SUM(TotalPrice) AS TotalRevenue
FROM ecommerce_data
GROUP BY Product
ORDER BY TotalRevenue DESC
"""

pd.read_sql(query, conn)

   Product  TotalRevenue
0    Chair     195620.11
1  Printer     195612.61
2   Laptop     192126.56
3   Tablet     186568.95
4  Monitor     175651.41
5     Desk     167459.93
6    Phone     151722.39

# AVG Aggregation

In [ ]:
query = """
SELECT Product, AVG(UnitPrice) AS AveragePrice
FROM ecommerce_data
GROUP BY Product
"""

pd.read_sql(query, conn)

   Product  AveragePrice
0    Chair    355.660281
1     Desk    329.608118
2   Laptop    357.707052
3  Monitor    358.663620
4    Phone    375.217564
5  Printer    351.714917
6   Tablet    367.679106

# Multiple Conditions

In [ ]:
query = """
SELECT Product, PaymentMethod, TotalPrice
FROM ecommerce_data
WHERE TotalPrice > 3000
AND OrderStatus = 'Delivered'
ORDER BY TotalPrice DESC
"""

pd.read_sql(query, conn)

   Product PaymentMethod  TotalPrice
0   Tablet        Online     3456.40
1   Laptop     Gift Card     3390.80
2  Printer    Debit Card     3334.00
3  Printer   Credit Card     3299.25
4    Chair        Online     3277.75
5    Phone     Gift Card     3170.00

# Referral Source Analysis

In [ ]:
query = """
SELECT ReferralSource, COUNT(*) AS TotalCustomers
FROM ecommerce_data
GROUP BY ReferralSource
ORDER BY TotalCustomers DESC
"""

pd.read_sql(query, conn)

  ReferralSource  TotalCustomers
0      Instagram             259
1          Email             250
2         Google             241
3       Facebook             228
4       Referral             222

# Coupon Usage Analysis

In [ ]:
query = """
SELECT CouponCode, COUNT(*) AS UsageCount
FROM ecommerce_data
GROUP BY CouponCode
ORDER BY UsageCount DESC
LIMIT 10
"""

pd.read_sql(query, conn)

           CouponCode  UsageCount
0            FREESHIP         313
1  Not use the Coupon         309
2            WINTER15         292
3              SAVE10         286